import { useMemo, useState } from 'react';
import { FiCheck, FiChevronRight, FiFlag, FiMap, FiMapPin } from 'react-icons/fi';
import { PageHeader } from '../components/PageHeader';
import { RouteMap } from '../components/RouteMap';
import { EmptyState, ErrorState, InlineLoader } from '../components/StatusViews';
import { useRoutesData } from '../hooks/useRoutesData';
import { formatDistance, sortedStops } from '../utils/format';

export default function RoutePage() {
  const { data: routes, loading, error, refresh } = useRoutesData();
  const [routeId, setRouteId] = useState('');
  const activeRoute = useMemo(() => routes?.find((route) => String(route.id) === routeId) || routes?.[0], [routeId, routes]);
  const stops = useMemo(() => sortedStops(activeRoute), [activeRoute]);
  const [currentStopId, setCurrentStopId] = useState('');
  const selectedIndex = Math.max(0, stops.findIndex((stop) => String(stop.id) === currentStopId));
  if (loading) return <InlineLoader label="Loading the official route timeline…" />;
  return <div className="content-page"><PageHeader eyebrow="The path to Pandhari" title="Route Timeline" description="Every stop below comes directly from the selected route’s stops collection." action={routes?.length > 1 ? <label className="select-label">Route<select value={routeId} onChange={(event) => setRouteId(event.target.value)}><option value="">{routes[0]?.routeName || 'First published route'}</option>{routes.slice(1).map((route) => <option key={route.id} value={route.id}>{route.routeName || `Route ${route.id}`}</option>)}</select></label> : null} />{error ? <ErrorState message={error} onRetry={refresh} /> : !activeRoute ? <EmptyState title="No route stops yet" detail="Create a route with its stops in the backend, then return here." /> : <><section className="route-overview"><div><span>Origin</span><b>{activeRoute.startLocation || stops[0]?.stopName || 'Not published'}</b></div><i /><div><span>Destination</span><b>{activeRoute.endLocation || 'Not published'}</b></div><i /><div><span>Total distance</span><b>{formatDistance(activeRoute.totalDistance)}</b></div><i /><div><span>Route stops</span><b>{stops.length}</b></div></section><section className="route-layout"><article className="timeline-card"><div className="card-heading"><div><span className="eyebrow">Your journey view</span><h2>Stops in sequence</h2></div></div><p className="timeline-explainer">Choose your current stop to personalize the visual status in this browser. The backend does not publish a current-stop field.</p><label className="current-stop-select">Mark my current stop<select value={currentStopId} onChange={(event) => setCurrentStopId(event.target.value)}><option value="">Beginning of the route</option>{stops.map((stop) => <option key={stop.id} value={stop.id}>{stop.stopNumber}. {stop.stopName}</option>)}</select></label>{stops.length ? <ol className="route-timeline">{stops.map((stop, index) => { const status = index < selectedIndex ? 'done' : index === selectedIndex ? 'current' : 'upcoming'; return <li key={stop.id} className={status}><span className="timeline-dot">{status === 'done' ? <FiCheck /> : status === 'current' ? <FiMapPin /> : <FiChevronRight />}</span><div><div className="stop-topline"><small>STOP {stop.stopNumber}</small>{stop.haltPoint && <em><FiFlag /> Mukkam</em>}</div><h3>{stop.stopName}</h3><p>{[stop.district, stop.taluka].filter(Boolean).join(' · ') || 'District and taluka not published'}</p></div><b>{formatDistance(stop.distanceFromStart)}</b></li>; })}</ol> : <EmptyState title="This route has no stops" detail="The route is returned by GET /routes, but its stops list is empty." />}</article><aside className="route-map-panel"><div className="card-heading"><div><span className="eyebrow">Map view</span><h2>Route path</h2></div><FiMap /></div><RouteMap stops={stops} selectedStopId={currentStopId ? Number(currentStopId) : stops[0]?.id} /></aside></section></>}</div>;
}
